repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.22
    hooks:
      - id: uv-lock
      - id: uv-export

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.377
    hooks:
      - id: pyright
